version: "3.8"

services:
  rl_research:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ghcr.io/vishgit1234/tdmpc2:latest
    command: /bin/bash -c "python3 -u train.py"
    # command: tail -f /dev/null
    env_file: "tdmpc2.env"
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./tdmpc2/logs/:/root/tdmpc2/logs/
      # - ./tdmpc2/:/root/tdmpc2/tdmpc2/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
