defaults:
    - override hydra/launcher: submitit_local

# environment
task: kinova_sweep
obs: state
episodic: false
num_envs: 2048
episode_length_s : 5
init_joint_angles: [6.9761, 1.1129, 1.7474, -2.2817, 7.5884, -1.1489, 1.6530, 0.8213, 0.8200, 0.8209, 0.8208, 0.8217, 0.8210]
init_quat: [0, 0, 0, 1]
bracelet_link_height: 0.25
init_box_pos: [0.2, 0.2, 0.002]
box_size: [0.08, 0.08, 0.02]
clip_actions: 0.01
termination_if_cube_goal_dist_less_than: 0.01
cube_goal_dist_rew_scale: 10
cube_arm_dist_rew_scale: 10
success_reward: 1
target_displacement: 0.3
action_scale: 0.01

# evaluation
checkpoint: ???
eval_episodes: 2048 # must be multiple of num_envs
eval_freq: 1_048_576 # must be a multiple of num_envs

# training
steps: 49_999_872 # should be multiple of num_envs
batch_size: 256
steps_per_update: 1024 # should be a divisor of num_envs
reward_coef: 0.1
value_coef: 0.1
termination_coef: 1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
exp_name: default
data_dir: ???

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 256
latent_dim: 128
task_dim: 96
num_q: 2
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: RL-Research
wandb_entity: vishalschool1234-university-of-waterloo
wandb_silent: false
enable_wandb: true
save_csv: false

# misc
compile: false
save_video: true
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???
