defaults:
    - override hydra/launcher: submitit_local

# environment
task: kinova_push_cube
obs: state
episodic: false
num_envs: 64
obs_buffer_size: 10
init_box_pos: [-0.3, 0.2]
box_gen_range: [0.1, 0.1]
box_size: [0.08, 0.08, 0.02]
termination_if_cube_goal_dist_less_than: 0.1
target_pos: [0., 0.2]
cube_half_sizes: [0.04, 0.04, 0.02]
action_scale: 0.5

# evaluation
checkpoint: ???
eval_episodes: 64 # must be multiple of num_envs
eval_freq: 99_968 # must be a multiple of num_envs

# training
steps: 1_000_000 # should be multiple of num_envs
batch_size: 512
steps_per_update: 64 # should be a divisor of num_envs
reward_coef: 0.1
value_coef: 0.1
termination_coef: 1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 99_968 # should be multiple of num_envs
exp_name: default
data_dir: ???
cuda_device: 0

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
use_stochastic_dynamics: false
model_size: ??? # preset config, below ignored
num_enc_layers: 2
enc_dim: 48
num_channels: 32
mlp_dim: 48
latent_dim: 32
task_dim: 96
num_q: 2
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: RL-Research
wandb_entity: vishalschool1234-university-of-waterloo
wandb_silent: false
enable_wandb: true
save_csv: false

# misc
compile: false
save_video: true
save_agent: true
seed: 2

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???
